root_dir: "/root/folder"
project_name: "LLLR_toymodel"
subproject_name: "LLLR_experiment"
name_dataset: "Multivariate_Gaussian"
root_tblogs: "/root/folder/tensorflow/logs/LLLR_toymodel/tblogs"
root_dblogs: "/root/folder/tensorflow/logs/LLLR_toymodel/dblogs"
root_ckptlogs: "/root/folder/tensorflow/logs/LLLR_toymodel/ckptlogs"

gpu: 0
max_to_keep: 3
exp_phase: 'stat'
comment: "LLLR" 

num_classes: 2
data_dim: 100
density_offset: 2
activation: "relu"
num_iter: 30000
train_display_step: 50
validation_step: 50

batch_size: 1000
learning_rates: [1e-4, 1e-4]
lr_decay_steps:  [100000000,]
weight_decay: 0.0001
name_optimizer: "adam"

flag_resume: False
path_resume: "/root/folder/tensorflow/logs/LLLR_toymodel/ckptlogs"
flag_seed: False
flag_wd: True
seed: 7

param_CE_loss: 0.
param_LLR_loss: 1.
param_LLLR_v2: 0.
param_KLIEP_loss: 0.
